name: Green IT Pipeline (Eco-CI Test)

on:
  push:
    branches: [ "main" ]

jobs:
  sustainability-test:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🟢 ECO-CI - Start Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: start-measurement

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 📦 Install dependencies
        run: |
          pip install -r requirements.txt

      - name: 🛠️ Run Eva's Script (Roche Device Carbon Estimator)
        run: |
          export CLOUD_PROVIDER="local"
          export CLOUD_REGION="ES"
          export CLOUD_INSTANCE_TYPE="github-runner"
          python carbon_script.py

      - name: 🛑 ECO-CI - Calculate Final Emissions
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          display-table: true
          pr-comment: true
